### PR TITLE
PRIM-192 with Miscellaneous Settings

### PR DESCRIPTION
**Pull request by JPPrimus123**
Miscellaneous Settings PRIM 266

### CODE REVIEW

**Comment by ahaynes91** [comment]
Regarding the conversation I had with Niruti, the only section that was worth automating in the "Miscellaneous Settings" was "SBO Screen Settings" since that can be easily validated on the UI, per the screenshots provided below:
image
image

Validating any changes made to the "Loan Term Refinance Settings" is more difficult since that relies on precise setup of an applicant's liabilities that can produce such results returned (or not returned) from the engine (what is displayed in the SBO solution steps).

Please make the necessary changes.

**Review by ahaynes91 — CHANGES_REQUESTED** [review]
See previous comment

**Review by ahaynes91 — CHANGES_REQUESTED** [review]
This test doesn't make sense mainly because the validation is not being performed on what was changed in the bank settings. This is why I said in the previous comments that it is not worth testing "Enable Remaining Loan Term Refinance Check" or "Enable Institution Minimum Month Refinance Check" due to the complexity of their respective validations in the UI.

If you have an application that has an SBO, you can test "Enable Adjustable DTI Threshold" very easily since that controls the visibility of the DTI component on the SBO.

**Comment by JPPrimus123** [comment]
Ok Alex
________________________________

**Pull request merged**
